# Generated by Django 5.2.5 on 2025-09-16 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="notification_days_before",
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name="company",
            name="notification_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="notify_slack",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="company",
            name="slack_webhook_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscribedcompanies",
                to="company.company",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscriptionsPlan",
                to="company.subscriptionplan",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["subscription", "status"], name="payments_subscri_500936_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["status", "payment_date"], name="payments_status_811742_idx"
            ),
        ),
    ]
