# Generated by Django 5.2.5 on 2025-09-16 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_company_notification_days_before_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="company.company",
            ),
        ),
    ]
